// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPzeRBHmcFyoPQJMAcb8Bw9WRin9ICV3I',
    appId: '1:1061747531103:web:8d5f851c0781b908b7eaea',
    messagingSenderId: '1061747531103',
    projectId: 'doctorappointment-dec07',
    authDomain: 'doctorappointment-dec07.firebaseapp.com',
    storageBucket: 'doctorappointment-dec07.firebasestorage.app',
    measurementId: 'G-528HM7JYWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtAugVnes1CODl7f_eJCPMm61oTx2P2M',
    appId: '1:1061747531103:android:6400b4e6f6df8e76b7eaea',
    messagingSenderId: '1061747531103',
    projectId: 'doctorappointment-dec07',
    storageBucket: 'doctorappointment-dec07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrlHWWDq3Ed-qBVjNkCwiHAQV_HHer01o',
    appId: '1:1061747531103:ios:f4b322d075f82783b7eaea',
    messagingSenderId: '1061747531103',
    projectId: 'doctorappointment-dec07',
    storageBucket: 'doctorappointment-dec07.firebasestorage.app',
    iosBundleId: 'com.example.doctorappoinmentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrlHWWDq3Ed-qBVjNkCwiHAQV_HHer01o',
    appId: '1:1061747531103:ios:f4b322d075f82783b7eaea',
    messagingSenderId: '1061747531103',
    projectId: 'doctorappointment-dec07',
    storageBucket: 'doctorappointment-dec07.firebasestorage.app',
    iosBundleId: 'com.example.doctorappoinmentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPzeRBHmcFyoPQJMAcb8Bw9WRin9ICV3I',
    appId: '1:1061747531103:web:55dbd08110a674d9b7eaea',
    messagingSenderId: '1061747531103',
    projectId: 'doctorappointment-dec07',
    authDomain: 'doctorappointment-dec07.firebaseapp.com',
    storageBucket: 'doctorappointment-dec07.firebasestorage.app',
    measurementId: 'G-WBGWYV85Q6',
  );
}
